---
# tasks file for ansible-role-nrpe

- include_tasks: add_additional_nrpe_checks.yml
  when: additional_nrpe_checks is defined

- include_tasks: user.yml
  when: nrpe_user_creation

- include_tasks: sudo.yml
  when: nrpe_disable_sudo_requiretty

- include_tasks: opsview.yml
  when: ansible_os_family == "RedHat" and install_opsview and not install_nrpe

- include_tasks: nrpe.yml
  when: not install_opsview and install_nrpe
