---
# tasks file for ansible-role-nrpe
#
- name: Set the service name for NRPE in Ubuntu
  set_fact:
    nrpe_service_name: nagios-nrpe-server
  when: ansible_facts["lsb"]["id"] == "Ubuntu"

- name: Set the service name for NRPE in non-Ubuntu
  set_fact:
    nrpe_service_name: nrpe
  when: ansible_facts["lsb"]["id"] != "Ubuntu"

- name: Compile and install in Raspbian
  import_tasks: install_raspbian.yml
  when: ansible_facts["lsb"]["id"] == 'Raspbian'

- name: Install nrpe DEB package
  package:
    state: present
    name: nagios-nrpe-server
  notify:
    - "restart nrpe"
  when: ansible_facts["lsb"]["id"] == "Ubuntu"

- name: Install nrpe RPM package
  package: state=present name=nrpe
  notify:
    - "restart nrpe"
  when: ansible_os_family == 'RedHat'

- name: Install extra nrpe RPMs
  package:  state=present name="{{ nrpe_extra_rpms }}"
  notify:
    - "restart nrpe"
  when: ansible_os_family == 'RedHat'

- name: Install extra nrpe DEBs
  package:  state=present name="{{ nrpe_extra_debs }}"
  notify:
    - "restart nrpe"
  when: ansible_facts["lsb"]["id"] == "Ubuntu"

- name: Remove all hardcoded command settings from default nrpe.cfg
  lineinfile:
    state: absent
    regexp: '^command\['
    path: '/etc/nagios/nrpe.cfg'
    backup: yes
  notify:
    - "restart nrpe"
  when: remove_hardcoded_checks|default(false)|bool

- name: Ensure NRPE group exists
  group:
    name: "{{ nrpe_group }}"

- name: Ensure NRPE user exists
  user:
    name: "{{ nrpe_user }}"
    group: "{{ nrpe_group }}"

- name: Ensure Nagios include dir exists
  file:
    path: "{{ nagios_include_dir }}"
    state: directory
    owner: "{{ nrpe_user }}"
    group: "{{ nrpe_group }}"

- name: Template in override config file (to set allowed_hosts)
  template: src=override.cfg.j2 dest={{ nagios_cfg_file }} mode=0644
            owner={{ nrpe_user }} group={{ nrpe_group }}
  notify:
    - "restart nrpe"

- name: Ensure default config file exists
  file:
    path: /etc/nagios/nrpe.cfg
    state: touch
  notify:
    - "restart nrpe"

- name: Ensure inclusion of other config files
  lineinfile:
    path: /etc/nagios/nrpe.cfg
    line: "include={{ nagios_include_dir }}"
    backup: yes
  notify:
    - "restart nrpe"

- name: Template in custom checks config file
  template: src=check_nagios.cfg.j2
            dest={{ nagios_include_dir }}/{{ nagios_custom_checks_file }}
            mode=0640
            owner={{ nrpe_user }} group={{ nrpe_group }}
  tags: update_nrpe_cfg
  notify:
    - "restart nrpe"

- name: Make sure nrpe is started and enabled in RedHat
  service:
    name: nrpe
    state: started
    enabled: yes
  when: ansible_os_family == 'RedHat' or ansible_facts["lsb"]["id"] == "Debian"

- name: Make sure nrpe is started and enabled in Ubuntu
  service:
    name: nagios-nrpe-server
    state: started
    enabled: yes
  when: ansible_facts["lsb"]["id"] == "Ubuntu"

- name: Allow nrpe_user to run some HP commands on HP systems
  template: src=sudoers_nrpe_hp dest=/etc/sudoers.d/sudoers_nrpe_hp mode=640
  when: ansible_system_vendor == "HP"
