---
# tasks file for ansible-role-nrpe

- name: Creating nagios group
  group:
    name: nagios
    gid: "{{ nagios_gid }}"
    state: present

- name: Creating nagios user
  user:
    name: nagios
    uid: "{{ nagios_uid }}"
    group: nagios
    comment: "nagios user"
    home: "{{ nagios_user_home }}"
    shell: /bin/bash
    state: present
