---
# handlers file for ansible-role-nrpe
#
- name: Set the service name for NRPE in Ubuntu
  set_fact:
    nrpe_service_name: nagios-nrpe-server
  when: ansible_facts["distribution"] == "Ubuntu" or ansible_facts["distribution"] == "Pop!_OS"

- name: Set the service name for NRPE in non-Ubuntu
  set_fact:
    nrpe_service_name: nrpe
  when: ansible_facts["distribution"] == "Debian" or ansible_os_family == 'RedHat'

- name: SELinux context changed
  command: "restorecon {{ item[0].script_path + item[1].script_name }}"
  with_subelements:
    - "{{ additional_nrpe_checks }}"
    - commands
  when: item[1].setype is defined

- name: restart nrpe
  service:
    name: "{{ nrpe_service_name }}"
    state: restarted
  listen: restart nrpe

- name: restart opsview-agent
  service: name=opsview-agent state=restarted
  